//Get Player Pokemon
export const REQUEST_PLAYER_POKE_PENDING = 'REQUEST_PLAYER_POKE_PENDING';
export const REQUEST_PLAYER_POKE_SUCCESS = 'REQUEST_PLAYER_POKE_SUCCESS';
export const REQUEST_PLAYER_POKE_FAILED = 'REQUEST_PLAYER_POKE_FAILED';

//Get Enemy Pokemon
export const REQUEST_ENEMY_POKE_PENDING = 'REQUEST_ENEMY_POKE_PENDING';
export const REQUEST_ENEMY_POKE_SUCCESS = 'REQUEST_ENEMY_POKE_SUCCESS';
export const REQUEST_ENEMY_POKE_FAILED = 'REQUEST_ENEMY_POKE_FAILED';

//Get Initial Score
export const SCORE_ZERO = 'SCORE_ZERO';

//Round Win
export const WIN_ROUND = 'WIN_ROUND'

//Poke Steal
export const POKE_STEAL = 'POKE_STEAL'