//Get Player Pokemon
export const REQUEST_PLAYER_POKE_PENDING = 'REQUEST_PLAYER_POKE_PENDING';
export const REQUEST_PLAYER_POKE_SUCCESS = 'REQUEST_PLAYER_POKE_SUCCESS';
export const REQUEST_PLAYER_POKE_FAILED = 'REQUEST_PLAYER_POKE_FAILED';

//Get Enemy Pokemon
export const REQUEST_ENEMY_POKE_PENDING = 'REQUEST_ENEMY_POKE_PENDING';
export const REQUEST_ENEMY_POKE_SUCCESS = 'REQUEST_ENEMY_POKE_SUCCESS';
export const REQUEST_ENEMY_POKE_FAILED = 'REQUEST_ENEMY_POKE_FAILED';

//Get Initial Score
export const SCORE_ZERO = 'SCORE_ZERO';

//Round Win
export const WIN_ROUND = 'WIN_ROUND';

//Poke Steal
export const POKE_STEAL = 'POKE_STEAL';
export const POKE_STEAL_DISCARD_POKE = 'POKE_STEAL_DISCARD_POKE';
export const POKE_STEAL_STEAL_POKE = 'POKE_STEAL_STEAL_POKE'

//Turn
export const TURN_DATA_MAINMENU = 'TURN_DATA_MAINMENU';
export const TURN_DATA_GAMESTART = 'TURN_DATA_GAMESTART';
export const TURN_DATA_WIN = 'TURN_DATA_WIN';
export const TURN_DATA_STEAL = 'TURN_DATA_STEAL';
export const TURN_DATA_LOSS = 'TURN_DATA_LOSS';

//Controls for the control box
export const VIEW_TEAM_STATS = 'VIEW_TEAM_STATS';
export const VIEW_CONTROLS_MAIN = 'VIEW_CONTROLS_MAIN';